---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  vars:
    irules: ['1.7.1-irule1', '1.7.2-irule2']

  tasks:
    - name: ADD iRules
      bigip_irule:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ f5_username }}"
          password: "{{ f5_password }}"
          server_port: 8443
          validate_certs: false
        module: "ltm"
        name: "{{ item }}"
        content: "{{ lookup('file','{{item}}') }}"
      with_items: "{{ irules }}"

    - name: ATTACH iRules TO VIRTUAL SERVER
      bigip_virtual_server:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ f5_username }}"
          password: "{{ f5_password }}"
          server_port: 8443
          validate_certs: false
        name: "vip"
        irules: "{{ irules }}"
...
