---
- name: setup webservers
  hosts: webservers
  
  pre_tasks:
     - raw: sudo dnf -y install python3
     
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: copy index.html
      template:
        src: index.j2
