---
- name: setup webservers
  hosts: webservers
  become: yes
  become_method: sudo
  
  pre_tasks:
     - raw: sudo dnf -y install python3
     
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started
        enablled: true

    - name: copy index.html
      template:
        src: index.j2
        dest: /var/www/html/index.html
